language: python
python:
    - "3.6"

install:
  - pip3 install poetry
  - poetry install

script:
  - poetry run nosetests

notifications:
  email:
    recipients:
      - asoli@fb.com
      - cmarchent@fb.com
    on_failure: change # default: always
